# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build'
    - task: ArchiveFiles@2
      displayName: 'Train Schedule Archive'
      inputs:
        archiveType: zip
        archiveFile: '$(System.DefaultWorkingDirectory)/dist/trainSchedule.zip'
        includeRootFolder: false
        replaceExistingArchive: true
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/dist/trainSchedule.zip'
        ArtifactName: "trainSchedule"
        PathtoPublish: '$(System.DefaultWorkingDirectory)/dist/'

- stage: BuildDockerImage
  displayName: Build  docker image
  jobs:
  - job: BuildImage
    displayName: Build Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
        arguments: '-t my23/train-schedule:$(tag)'
    - script: |
        docker images
#        docker run MY23/cicd-pipeline-train-schedule-dockerdeploy:$(tag)
      displayName: 'Test Dockerfile Build'